### ISSUE TITLE
Misses

### ISSUE THREAD

**Issue by Faact** [mrflashstudio/Quack#20] opened 2021-08-04 01:52 UTC
I am having the same problem with the other guy, but I miss on every single map, I try osu maps, ranked maps, unranked maps, and even pending maps. All of them don't seem to work, I'll try doing it with faster speeds, but otherwise, the bot isn't doing well rn.

**Comment by Faact** [comment] 2021-08-04 01:54
I am using 4k btw.

**Comment by mrflashstudio** [comment] 2021-08-04 09:37
Duplicate of #6

**Closed as completed by mrflashstudio** 2021-08-04 09:37 UTC
